POST http://127.0.0.1:8000/api/reset-password
Content-Type: : : application/json
Accept:  application/json

{
    "email": "bladi@gmail.com"
}


### CAMBIO DE CONTRASEÑA
POST http://127.0.0.1:8000/api/change-password
Content-Type: : : application/json
Accept:  application/json

{
    "token": "dsfghj",
    "email": "bladi@gmail.com",
    "password": "bladi12345",
    "password_confirmatio":"bladi12345"
}